name: todo
services:
  server:
    container_name: todo_server
    ports:
      - 4000:4000
    image: todo_server:latest
    depends_on:
      - mysql
  mysql:
    container_name: todo_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=todo
    image: mysql:latest
