CREATE TABLE IF NOT EXISTS Tasks(
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    Text VARCHAR (255) ,
    IsDone BOOLEAN,
    UserID INT ,
    FOREIGN KEY (UserID) REFERENCES Users(ID) ,
    PRIMARY KEY (ID)
)
