// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTask struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Result struct {
	IsSuccessful bool `json:"isSuccessful"`
}

type Task struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	IsDone bool   `json:"isDone"`
	User   *User  `json:"user"`
}

type UpdatedTask struct {
	ID     string `json:"id"`
	IsDone bool   `json:"isDone"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
